name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - feature/tests
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Upgrade pip and setuptools
      run: |
        python -m pip install --upgrade pip setuptools

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python -m unittest discover -s tests

    - name: Trigger Render Deploy Hook
      env:
        RENDER_DEPLOY_HOOK_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
      run: |
        if [ -z "$RENDER_DEPLOY_HOOK_URL" ]; then
          echo "RENDER_DEPLOY_HOOK_URL is not set"
          exit 1
        fi
        curl -X POST "$RENDER_DEPLOY_HOOK_URL"
